
library(NLP)
library(dplyr)
library(readtext)
library(tm)
library(stringi)
library(stringr)
library(lattice)
library(ggplot2)
library(ddalpha)
library(caret)
library(LaF)
library(tidytext)
library(tidyr)
library(ff)
library(knitr)
library(cowplot)
library(kableExtra)
library(filehash)
library(readr)
library(data.table)

#read in data sets
setwd("C:/Users/hlevy/Documents/R/SwiftKey/final/en_US")
blogLines <- determine_nlines("C:/Users/hlevy/Documents/R/SwiftKey/final/en_US/en_US.blogs.txt")
blogs4Text <- read.table("en_US.blogs.txt", fill = TRUE, nrows = 899288, sep = "")
blogs4Text <- saveRDS(blogs4Text, "blogs4Text.RDS")
blogs4Text <- read_rds("blogs4Text.RDS")
newsLines <- determine_nlines("C:/Users/hlevy/Documents/R/SwiftKey/final/en_US/en_US.news.txt")
news4Text <- read.table("en_US.news.txt", fill = TRUE, nrows = 1010242, sep = "")
news4Text <- saveRDS(news4Text, "news4Text.RDS")
news4Text <- read_rds("news4Text.RDS")
twitterLines <- determine_nlines("C:/Users/hlevy/Documents/R/SwiftKey/final/en_US/en_US.twitter.txt")
twitter4Text <- read.table("en_US.twitter.Rdata", fill = TRUE, nrows = 2360148, sep = "", header=F,encoding="latin1", quote="", comment='')
twitter4Text <- saveRDS(twitter4Text, "twitter4Text.RDS")
twitter4Text <- read_rds("twitter4Text.RDS")

#basic cleaning before subdividing the data, decided to eliminate in sentence punctution. Keep end of sentence punctution
blogs4Text <- blogs4Text %>% dplyr::mutate(text = tolower(text))
blogs4Text <- blogs4Text %>% dplyr::filter(!is.na(text))
blogs4Text <- blogs4Text %>% dplyr::mutate(str_extract(number, "[0-9']+"))
blogs4Text <- gsub(",", "", blogs4Text)
blogs4Text <- gsub(";", "", blogs4Text)
blogs4Text <- gsub("-", "", blogs4Text)
blogs4Text <- gsub(":", "", blogs4Text)
blogs4Text <- gsub("()", "", blogs4Text)
blogs4Text <- gsub("$", "", blogs4Text)
blogs4Text <- gsub("%", "", blogs4Text)
blogs4Text <- gsub("@", "", blogs4Text)
blogs4Text <- gsub("*", "", blogs4Text)

#create training, validation and test sets
bloginTrain <- createDataPartition(y=blogs4Text, p =.6, list = FALSE)
blogtraining <- blogs4Text[bloginTrain, ]
blogvalidation <- blogs4Text[-bloginTrain, ]